# Generated by Django 4.2.2 on 2023-07-29 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addressapp', '0006_profile_user_alter_profile_email_usercontact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile',
        ),
        migrations.AddField(
            model_name='usercontact',
            name='profile',
            field=models.ForeignKey(default=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='addressapp.profile'),
        ),
    ]
