# Generated by Django 4.2.2 on 2023-07-29 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressapp', '0010_profile_profile_alter_profile_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile',
        ),
    ]
